# Generated by Django 6.0.4 on 2026-04-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_docente_formacao_makingof_tecnologia_projeto_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tfc",
            old_name="area",
            new_name="autor",
        ),
        migrations.RenameField(
            model_name="tfc",
            old_name="instituicao",
            new_name="curso",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="descricao",
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=500),
        ),
    ]
