# Generated by Django 6.0.4 on 2026-05-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_tipotecnologia_remove_tecnologia_categoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="curso",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(max_length=500),
        ),
    ]
