# Generated by Django 6.0.4 on 2026-05-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_alter_tfc_autor_alter_tfc_curso_alter_tfc_orientador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="curso",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.TextField(),
        ),
    ]
